export const sampleDataStructure = {
	leagues: [
		{
			id: 1,
			upcomingGames: [
				{
					match_week: 1,
					league_id: 1,
					match_day: 'Sunday',
					game_date: '17-06-2021',
					match_time: '16:00',
					blue_team: 'TSM',
					red_team: 'CLG',
				},
				{
					match_week: 1,
					league_id: 1,
					match_day: 'Sunday',
					game_date: '17-06-2021',
					match_time: '16:00',
					blue_team: 'TSM',
					red_team: 'CLG',
				},
			],
			leagueTeams: {
				id: 1,
				name: 'Team SoloMid',
				league: 1,
				logo: 'TSM',
			},
			currentMatch: {
				league: 1,
				teamOne: 'Team SoloMid',
				teamTwo: 'CLG',
				date: '17-06-2021',
				results: {
					gameId: 1,
					firstBlood: 'tsm',
					firstTower: 'tsm',
					firstDragon: 'clg',
					firstInhibitor: 'tsm',
					firstBaron: 'clg',
					winner: 'clg',
					loser: 'tsm',
				},
				odds: {
					gameId: 1,
					teamOne: 'tsm',
					teamTwo: 'clg',
					teamOneWin: 1.56,
					teamTwoWin: 1.51,
					teamOneFirstBlood: 1.76,
					teamTwoFirstBlood: 1.32,
					teamOneFt5Kills: 1.94,
					teamTwoFt5Kills: 1.73,
					teamOneFt10Kills: 1.69,
					teamTwoFt10Kills: 1.91,
					oddKills: 1.82,
					evenKills: 1.23,
				},
			},
		},
		{
			id: 2,
			upcomingGames: {},
			leagueTeams: {
				id: 2,
				name: 'FunPlus Phoenix',
				league: 2,
				logo: 'fpx',
			},
			currentMatch: {
				league: 2,
				teamOne: 'FunPlus Phoenix',
				teamTwo: 'T1',
				date: '27-06-2022',
				results: {
					gameId: 2,
					firstBlood: 'fpx',
					firstTower: 'fpx',
					firstDragon: 't1',
					firstInhibitor: 'fpx',
					firstBaron: 't1',
					winner: 't1',
					loser: 'fpx',
				},
				odds: {
					gameId: 2,
					teamOne: 'fpx',
					teamTwo: 't1',
					teamOneWin: 2.56,
					teamTwoWin: 2.52,
					teamOneFirstBlood: 2.76,
					teamTwoFirstBlood: 2.32,
					teamOneFt5Kills: 2.94,
					teamTwoFt5Kills: 2.73,
					teamOneFt20Kills: 2.69,
					teamTwoFt20Kills: 2.92,
					oddKills: 2.82,
					evenKills: 2.23,
				},
			},
		},
	],
}
